# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43cd463078e65a232945b7f7b410bfda97700696002d4b7513a094996abe5ccde65ca9edfd1cbf64eef30990234c140bf2d795103ad15e068fdf88c349bb886

test:
  secret_key_base: c5070c6097ad615bc7616b86e5dcf9146909277c18d203a49f136bbdf51ed35740ab80e4e537547343507260bb6095176d428c7c4ae1327792ba870caafa2c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
